services:
  n8n:
    image: n8nio/n8n:latest
    container_name: smartnewsai_n8n
    restart: always
    ports:
      - "5678:5678"  # Map cổng container ra VPS
    env_file:
      - .env    # file bạn đã tạo
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD}
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
    volumes:
      - ./n8n_data:/home/node/.n8n   # Lưu workflow, credentials, database
    user: "1000:1000"   # chạy container bằng UID node
