version: "3.9"

services:
  backend:
    build:
      context: .           # vì Dockerfile nằm trong server/
      dockerfile: Dockerfile
    container_name: smartnewsai_backend
    env_file:
      - .env            # 👈 file .env nằm ở ngoài thư mục server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app/server            # mount toàn bộ server/ vào container /app
    command: >
      bash -lc "uvicorn server.main:app --host 0.0.0.0 --port 8000 --reload"
  n8n:
    image: n8nio/n8n:latest
    container_name: smartnewsai_n8n
    ports:
      - "5680:5678"                     # truy cập n8n qua http://localhost:5678
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_USER}         # từ file .env
      - N8N_BASIC_AUTH_PASSWORD=${N8N_PASSWORD} # từ file .env
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
    volumes:
      - ./n8n_data:/home/node/.n8n      # nơi lưu workflow, credentials,...
    restart: always